version: '2'

services: 
    pycosmosdbbymongodb:
        image: pycosmosdbbymongodb
        build: .
        command: python main.py
        volumes: 
            - .:/src
        environment: 
            MONGO_DB: ${MONGO_DB}
            MONGO_HOST: ${MONGO_HOST}
            MONGO_USERNAME: ${MONGO_USERNAME}
            MONGO_PASSWORD: ${MONGO_PASSWORD}